[tool.poetry]
name = "who-is-that"
version = "0.1.0"
description = "Generate spoiler-free summaries of characters up-to-a-given-point in a text"
authors = [
    "James Robinson <james.em.robinson@gmail.com>"
]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
ollama = "^0.2.1"
ebooklib = "^0.18"
bs4 = "^0.0.2"

[tool.poetry.scripts]
extract = "who_is_that.entrypoint:extract"
summarise = "who_is_that.entrypoint:summarise"

[tool.poetry.group.dev.dependencies]
ipykernel = "^6.29.4"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
