---
services:
  backend:
    container_name: backend
    build:
      context: ..
      dockerfile: docker/backend.Dockerfile
    environment:
      OLLAMA_HOST: "http://host.docker.internal"
      OLLAMA_MODEL: "llama3:8b"
      OLLAMA_PORT: "11434"
    ports:
      - "127.0.0.1:3000:5000"
  frontend:
    container_name: frontend
    build:
      context: ..
      dockerfile: docker/frontend.Dockerfile
    environment:
      BACKEND_HOST: "http://backend"
      BACKEND_PORT: "5000"
    ports:
      - "127.0.0.1:4000:5000"
