"Pride and Prejudice": 
  author: "Jane Austen"
  characters: 
    "Mr. Wickham":
      spoilers:
        - "Mr. Wickham betrays the trust of the Bennet family by eloping with Lydia Bennet, the youngest daughter."
"A Game of Thrones": 
  author: "George R. R. Martin"
  characters: 
    "Jon Snow":
      spoilers:
        - "Jon Snow is the son of Lyanna Stark and Rhaegar Targaryen, making him the legitimate heir to the Iron Throne; Aegon Targaryen."
"Harry Potter and the Half-Blood Prince":
  author: "J. K. Rowling"
  characters:
    "Albus Dumbledore":
      spoilers:
        - "Albus Dumbledore is killed by Severus Snape."